#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@ Generated by Claude
"""
"""
migrate_list_to_v2.py

Переносит треки (id -> url аудиопотока) из list.json в list_v2.json,
в source с supportedVersion == ">0.0.0" (в его tracksStorages).

Правило распределения:
  - если id трека совпадает с последним сегментом url (частью после
    последнего "/"), трек добавляется в tracksStorages[].trackIds;
  - иначе трек добавляется в tracksStorages[].tracks[str(id)].

durationMs получается скачиванием аудиофайла по ссылке и чтением его
метаданных через mutagen/ffprobe (локально длительность не хранится).
Эта измеренная длительность сравнивается с durationMs, которую отдаёт
Yandex Music API для того же id (через библиотеку yandex_music, по
образцу append_track.py):
  - если разница в пределах допуска (--tolerance-ms) - считаем, что
    длительности совпадают, и пишем "голое" значение: просто число id
    в trackIds, просто строку url в tracks (клиент и так знает верную
    длительность из самого Yandex Music API);
  - если разница больше допуска (или Yandex Music не отдал данные по
    этому id) - пишем объект {"id"/"url", "durationMs"} с измеренной
    длительностью, чтобы явно её переопределить.

list.json НЕ изменяется - он остаётся исходным источником данных
(так решили при уточнении задачи).

Использование:
    python migrate_list_to_v2.py
    python migrate_list_to_v2.py --list list.json --list-v2 list_v2.json --output list_v2.json
    python migrate_list_to_v2.py --dry-run                 # быстрая проверка распределения id, без скачивания
    python migrate_list_to_v2.py --limit 20 --workers 8     # тестовый прогон на 20 треках
    python migrate_list_to_v2.py --force                    # переобработать уже перенесённые id
    python migrate_list_to_v2.py --tolerance-ms 500         # допуск сравнения с Yandex Music API (по умолчанию 500)
    python migrate_list_to_v2.py --skip-api-check           # не ходить в Yandex Music API, всегда писать явный durationMs

Токен Яндекс.Музыки берётся из переменной окружения API_TOKEN (в т.ч.
из .env файла, как в append_track.py). Без токена клиент работает в
анонимном режиме - этого достаточно для получения durationMs треков.

Скрипт устойчив к прерываниям (Ctrl+C) и падениям сети:
  - длительности кешируются в duration_cache.json, поэтому повторный
    запуск не скачивает повторно уже обработанные файлы (в т.ч. если
    несколько id ссылаются на один и тот же аудиофайл);
  - id, уже присутствующие в list_v2.json, по умолчанию пропускаются,
    так что скрипт можно перезапускать сколько угодно раз, пока не
    будут перенесены все треки;
  - не обработанные из-за ошибок id сохраняются в failed_tracks.json
    для дальнейшего анализа/повтора;
  - если Yandex Music API недоступен, скрипт не падает, а просто пишет
    для всех треков явный durationMs (как будто везде расхождение).
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from io import BytesIO

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

try:
    import mutagen
except ImportError:
    sys.exit(
        "Не найден модуль mutagen. Установите его командой:\n"
        "    pip install mutagen --break-system-packages"
    )

try:
    from yandex_music import Client as YandexClient
    from yandex_music.exceptions import YandexMusicError
except ImportError:
    sys.exit(
        "Не найден модуль yandex_music. Установите его командой:\n"
        "    pip install yandex-music --break-system-packages"
    )

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv не обязателен - можно задать API_TOKEN прямо в окружении

# ffprobe используется как запасной вариант для файлов, метаданные которых
# mutagen не может корректно разобрать (например, некоторые фрагментированные
# mp4/m4a без длительности в moov-атоме). Если ffprobe не установлен, такие
# треки будут считаться ошибочными и попадут в failed_tracks.json.
FFPROBE_PATH = shutil.which("ffprobe")


DEFAULT_LIST = "list.json"
DEFAULT_LIST_V2 = "list_v2.json"
DEFAULT_CACHE = "duration_cache.json"
DEFAULT_FAILED = "failed_tracks.json"
TARGET_SUPPORTED_VERSION = ">0.0.0"
DEFAULT_TOLERANCE_MS = 500
DEFAULT_API_BATCH_SIZE = 200


# --------------------------------------------------------------------------- #
# HTTP
# --------------------------------------------------------------------------- #

def build_session() -> requests.Session:
    session = requests.Session()
    retry = Retry(
        total=3,
        backoff_factor=1.5,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"],
    )
    adapter = HTTPAdapter(max_retries=retry, pool_maxsize=32)
    session.mount("https://", adapter)
    session.mount("http://", adapter)
    return session


_thread_local = threading.local()


def get_session() -> requests.Session:
    if not hasattr(_thread_local, "session"):
        _thread_local.session = build_session()
    return _thread_local.session


def duration_via_ffprobe(data: bytes, timeout: float):
    """Пробует получить длительность через ffprobe. Возвращает durationMs или None."""
    if not FFPROBE_PATH:
        return None
    tmp = tempfile.NamedTemporaryFile(suffix=".audio", delete=False)
    temp_path = tmp.name
    try:
        tmp.write(data)
        tmp.close()
        try:
            proc = subprocess.run(
                [FFPROBE_PATH, "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", temp_path],
                capture_output=True, text=True, timeout=timeout,
            )
        except (subprocess.TimeoutExpired, OSError) as e:
            print("Failed to run ffprobe", e)
            return None
    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)
    if proc.returncode != 0:
        print("Failed to run ffprobe", proc.stderr)
        return None
    try:
        seconds = float(proc.stdout.strip())
    except ValueError:
        print("Failed to parse ffprobe output", proc.stdout)
        return None
    if seconds <= 0:
        return None
    return round(seconds * 1000)


def fetch_duration_ms(url: str, timeout: float) -> int:
    session = get_session()
    resp = session.get(url, timeout=timeout)
    resp.raise_for_status()
    data = resp.content

    # 1) быстрый путь - mutagen (без внешних зависимостей)
    audio = mutagen.File(BytesIO(data)) # type: ignore
    if audio is not None and audio.info is not None:
        length_seconds = getattr(audio.info, "length", 0)
        if length_seconds and length_seconds > 0:
            return round(length_seconds * 1000)

    # 2) запасной путь - ffprobe (надёжнее для некоторых mp4/m4a контейнеров)
    duration_ms = duration_via_ffprobe(data, timeout)
    if duration_ms is not None:
        return duration_ms

    hint = "" if FFPROBE_PATH else " (установите ffmpeg, чтобы включить запасной способ определения длительности)"
    raise ValueError(f"не удалось определить длительность{hint}")


# --------------------------------------------------------------------------- #
# Кеш длительностей (url -> durationMs), потокобезопасный, с записью на диск
# --------------------------------------------------------------------------- #

class DurationCache:
    def __init__(self, path: str):
        self.path = path
        self.lock = threading.Lock()
        self.data = {}
        if os.path.exists(path):
            try:
                with open(path, "r", encoding="utf-8") as f:
                    self.data = json.load(f)
            except (json.JSONDecodeError, OSError):
                print(f"[!] Не удалось прочитать кеш {path}, начинаю с пустого", file=sys.stderr)

    def get(self, url: str):
        with self.lock:
            return self.data.get(url)

    def set(self, url: str, duration_ms: int) -> None:
        with self.lock:
            self.data[url] = duration_ms
            self._flush()

    def _flush(self) -> None:
        directory = os.path.dirname(os.path.abspath(self.path)) or "."
        tmp_fd, tmp_path = tempfile.mkstemp(dir=directory, prefix=".dcache_")
        try:
            with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
                json.dump(self.data, f, ensure_ascii=False)
            os.replace(tmp_path, self.path)
        except Exception:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
            raise


# --------------------------------------------------------------------------- #
# Yandex Music API (для сверки durationMs)
# --------------------------------------------------------------------------- #

def build_yandex_client() -> YandexClient:
    """Создаёт клиент Yandex Music, как в append_track.py: с токеном из API_TOKEN,
    либо анонимно, если токена нет. init() нужен только для данных аккаунта,
    поэтому его падение не критично - просто продолжаем без него."""
    token = os.getenv("API_TOKEN")
    client = YandexClient(token) if token else YandexClient()
    try:
        client.init()
    except Exception as e:
        print(f"[!] Не удалось инициализировать аккаунт Yandex Music ({e}), продолжаю анонимно", file=sys.stderr)
    return client


def fetch_api_durations(client: YandexClient, ids, batch_size: int, retries: int = 2) -> dict:
    """Возвращает {id_str: durationMs} по данным Yandex Music API.
    Id, которые не удалось получить (сеть/бан/удалённый трек), просто отсутствуют
    в результате - для них позже будет использован явный durationMs."""
    ids = list(dict.fromkeys(ids))  # без дублей, с сохранением порядка
    durations: dict = {}
    total_batches = (len(ids) + batch_size - 1) // batch_size

    for batch_num, i in enumerate(range(0, len(ids), batch_size), start=1):
        batch = ids[i : i + batch_size]
        attempt = 0
        tracks = []
        while True:
            attempt += 1
            try:
                tracks = client.tracks(batch) or []
                break
            except YandexMusicError as e:
                if attempt > retries:
                    print(
                        f"[!] Yandex Music API: не удалось получить батч {batch_num}/{total_batches} "
                        f"после {attempt} попыток ({e}), эти {len(batch)} треков получат явный durationMs",
                        file=sys.stderr,
                    )
                    tracks = []
                    break
                time.sleep(1.5 * attempt)
            except Exception as e:
                # неожиданная ошибка (например обрыв сети) - не роняем весь скрипт
                if attempt > retries:
                    print(
                        f"[!] Yandex Music API: неожиданная ошибка на батче {batch_num}/{total_batches} ({e}), "
                        f"эти {len(batch)} треков получат явный durationMs",
                        file=sys.stderr,
                    )
                    tracks = []
                    break
                time.sleep(1.5 * attempt)

        for t in tracks:
            if t is None or t.duration_ms is None:
                continue
            durations[str(t.id)] = t.duration_ms

        print(f"Yandex Music API: батч {batch_num}/{total_batches}, всего получено {len(durations)}/{len(ids)}")

    return durations


# --------------------------------------------------------------------------- #
# Вспомогательная логика
# --------------------------------------------------------------------------- #

def last_url_segment(url: str) -> str:
    return url.rstrip("/").rsplit("/", 1)[-1]


def find_target_storage(list_v2: dict) -> dict:
    matches = [
        s for s in list_v2.get("sources", [])
        if s.get("supportedVersion") == TARGET_SUPPORTED_VERSION
    ]
    if not matches:
        sys.exit(f'Не найден source с supportedVersion == "{TARGET_SUPPORTED_VERSION}" в list_v2.json')
    if len(matches) > 1:
        print(
            f'[!] Найдено {len(matches)} source с supportedVersion == "{TARGET_SUPPORTED_VERSION}", '
            f"использую первый",
            file=sys.stderr,
        )
    source = matches[0]
    storages = source.get("tracksStorages") or []
    if not storages:
        sys.exit("В целевом source отсутствует tracksStorages - добавлять данные некуда")
    if len(storages) > 1:
        print("[!] В целевом source несколько tracksStorages, использую первый", file=sys.stderr)
    return storages[0]


def already_migrated_ids(storage: dict) -> set:
    ids = set()
    for entry in storage.get("trackIds", []):
        if isinstance(entry, dict):
            ids.add(str(entry.get("id")))
        else:
            ids.add(str(entry))
    ids.update(storage.get("tracks", {}).keys())
    return ids


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #

def main() -> None:
    parser = argparse.ArgumentParser(description="Перенос треков из list.json в list_v2.json")
    parser.add_argument("--list", default=DEFAULT_LIST, help="путь к list.json (источник, не изменяется)")
    parser.add_argument("--list-v2", default=DEFAULT_LIST_V2, help="путь к list_v2.json (куда переносим)")
    parser.add_argument("--output", default=None, help="куда сохранить результат (по умолчанию перезаписывает --list-v2)")
    parser.add_argument("--cache", default=DEFAULT_CACHE, help="файл кеша длительностей url -> durationMs")
    parser.add_argument("--failed", default=DEFAULT_FAILED, help="куда сохранить список не обработанных треков")
    parser.add_argument("--workers", type=int, default=8, help="число параллельных загрузок (по умолчанию 8)")
    parser.add_argument("--timeout", type=float, default=30.0, help="таймаут одного запроса, сек")
    parser.add_argument("--limit", type=int, default=None, help="обработать только первые N новых треков (для теста)")
    parser.add_argument("--force", action="store_true", help="переобработать id, уже присутствующие в list_v2.json")
    parser.add_argument(
        "--dry-run", action="store_true",
        help="только показать распределение id по trackIds/tracks, без скачивания и без записи файла",
    )
    parser.add_argument(
        "--tolerance-ms", type=int, default=DEFAULT_TOLERANCE_MS,
        help=f"допуск (мс) при сравнении измеренной длительности с durationMs из Yandex Music API "
             f"(по умолчанию {DEFAULT_TOLERANCE_MS})",
    )
    parser.add_argument(
        "--api-batch-size", type=int, default=DEFAULT_API_BATCH_SIZE,
        help=f"сколько id запрашивать у Yandex Music API за один запрос (по умолчанию {DEFAULT_API_BATCH_SIZE})",
    )
    parser.add_argument(
        "--skip-api-check", action="store_true",
        help="не обращаться к Yandex Music API - все треки получат явный durationMs (старое поведение)",
    )
    args = parser.parse_args()
    args.output = args.output or args.list_v2

    with open(args.list, "r", encoding="utf-8") as f:
        source_data = json.load(f)
    tracks_map: dict = source_data.get("tracks") or {}
    if not tracks_map:
        sys.exit("В list.json не найдено треков (свойство 'tracks' пустое или отсутствует)")

    with open(args.list_v2, "r", encoding="utf-8") as f:
        list_v2 = json.load(f)

    storage = find_target_storage(list_v2)
    had_tracks_key = "tracks" in storage

    skip_ids = set() if args.force else already_migrated_ids(storage)
    todo = [(tid, url) for tid, url in tracks_map.items() if tid not in skip_ids]
    skipped_count = len(tracks_map) - len(todo)
    if skipped_count:
        print(f"Пропускаю {skipped_count} уже перенесённых id (используйте --force для переобработки)")

    if args.limit is not None:
        todo = todo[: args.limit]

    template_ids = [tid for tid, url in todo if last_url_segment(url) == tid]
    explicit_ids = [tid for tid, url in todo if last_url_segment(url) != tid]
    print(
        f"К обработке: {len(todo)} треков "
        f"({len(template_ids)} по шаблону urlTemplate, {len(explicit_ids)} с явной ссылкой)"
    )

    if not todo:
        print("Нечего переносить.")
        return
    if args.dry_run:
        print("--dry-run: скачивание, запрос Yandex Music API и запись файла пропущены")
        return

    if args.skip_api_check:
        print("--skip-api-check: сверка с Yandex Music API отключена, все треки получат явный durationMs")
        api_durations = {}
    else:
        print("Запрашиваю официальные длительности треков в Yandex Music API...")
        yandex_client = build_yandex_client()
        api_durations = fetch_api_durations(yandex_client, [tid for tid, _ in todo], args.api_batch_size)
        if not api_durations:
            print(
                "[!] Не получено ни одной длительности из Yandex Music API - "
                "все треки будут сохранены с явным durationMs",
                file=sys.stderr,
            )

    cache = DurationCache(args.cache)

    def worker(tid: str, url: str):
        cached = cache.get(url)
        if cached is not None:
            return cached
        duration_ms = fetch_duration_ms(url, args.timeout)
        cache.set(url, duration_ms)
        return duration_ms

    results = {}   # tid -> (url, duration_ms)
    failures = []  # (tid, url, error)
    total = len(todo)
    done = 0
    progress_lock = threading.Lock()

    executor = ThreadPoolExecutor(max_workers=args.workers)
    future_to_item = {executor.submit(worker, tid, url): (tid, url) for tid, url in todo}
    try:
        for future in as_completed(future_to_item):
            tid, url = future_to_item[future]
            with progress_lock:
                done += 1
                progress = f"[{done}/{total}]"
            try:
                duration_ms = future.result()
                results[tid] = (url, duration_ms)
                print(f"{progress} OK   id={tid} duration={duration_ms}ms")
            except Exception as e:
                failures.append((tid, url, str(e)))
                print(f"{progress} FAIL id={tid} url={url} error={e}", file=sys.stderr)
    except KeyboardInterrupt:
        print("\nПрервано пользователем, отменяю оставшиеся задачи и сохраняю то, что уже обработано...", file=sys.stderr)
        executor.shutdown(wait=False, cancel_futures=True)
    else:
        executor.shutdown(wait=True)

    trackIds = storage.setdefault("trackIds", [])
    tracks = storage.setdefault("tracks", {})
    matched_count = 0
    mismatched_count = 0
    for tid, (url, duration_ms) in results.items():
        api_duration_ms = api_durations.get(tid)
        is_match = api_duration_ms is not None and abs(duration_ms - api_duration_ms) <= args.tolerance_ms
        if is_match:
            matched_count += 1
        else:
            mismatched_count += 1

        if last_url_segment(url) == tid:
            trackIds.append(int(tid) if is_match else {"id": int(tid), "durationMs": duration_ms})
        else:
            tracks[tid] = url if is_match else {"url": url, "durationMs": duration_ms}

    # не оставляем пустой "tracks", если его не было и добавлять оказалось нечего
    if not had_tracks_key and not tracks:
        del storage["tracks"]

    if not args.skip_api_check:
        print(
            f"Сверка с Yandex Music API: совпало (голое значение) - {matched_count}, "
            f"разошлось/неизвестно (явный durationMs) - {mismatched_count}"
        )

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(list_v2, f, ensure_ascii=False, indent=4)
        f.write("\n")

    print(f"\nГотово: перенесено {len(results)} треков, ошибок: {len(failures)}")
    if failures:
        with open(args.failed, "w", encoding="utf-8") as f:
            json.dump(
                {tid: {"url": url, "error": err} for tid, url, err in failures},
                f, ensure_ascii=False, indent=2,
            )
        print(f"Не обработанные треки сохранены в {args.failed} — просто запустите скрипт ещё раз, чтобы повторить попытку")

    print(f"Результат сохранён в {args.output}")


if __name__ == "__main__":
    main()